version: "3"
services:
  bat_backend:
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - 8080:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    depends_on:
      - fin_db_server
#  bat_frontend:
#    image: evershop/evershop:latest
#    restart: always
#    build:
#      context: ./frontend
#    environment:
#      DB_HOST: fin_db_server
#      DB_PORT: 5432
#      DB_PASSWORD: admin
#      DB_USER: admin
#      DB_NAME: fin_db
#    depends_on:
#      - fin_db_server
#    ports:
#      - 3000:3000
  fin_db_server:
    restart: always
    image: postgres:15
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  staticfiles:
  postgresql_data: