# Generated by Django 4.2 on 2024-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallanalysis',
            name='rank',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='overallanalysis',
            name='analysisResult',
            field=models.CharField(choices=[('GOOD', 'good'), ('BAD', 'bad'), ('OK', 'ok'), ('NAVL', 'navl')], max_length=6),
        ),
        migrations.AlterField(
            model_name='overallanalysis',
            name='metric',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('GROSSMARGIN', 'GrossMargin'), ('DERATIO', 'DERatio')], max_length=20),
        ),
    ]
