# Generated by Django 4.2 on 2024-02-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_overallanalysis_analysisresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallanalysis',
            name='max_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='symbolanalysis',
            name='max_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='symbolanalysis',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='symbolanalysis',
            name='AnalysisStatus',
            field=models.CharField(choices=[('VGOOD', 'vgood'), ('GOOD', 'good'), ('BAD', 'bad'), ('OK', 'ok')], max_length=6),
        ),
    ]
