# Generated by Django 4.2 on 2024-08-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_overallanalysis_max_rank_symbolanalysis_max_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='BasicAverageShares',
            new_name='AccountsPayable',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='BasicEPS',
            new_name='AccountsReceivable',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='CostOfRevenue',
            new_name='AccumulatedDepreciation',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='DilutedAverageShares',
            new_name='AvailableForSaleSecurities',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='DilutedEPS',
            new_name='CapitalLeaseObligations',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='DilutedNIAvailtoComStockholders',
            new_name='CapitalStock',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='EBIT',
            new_name='CashAndCashEquivalents',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='EBITDA',
            new_name='CashCashEquivalentsAndShortTermInvestments',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='GrossProfit',
            new_name='CashEquivalents',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='InterestExpense',
            new_name='CashFinancial',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='InterestExpenseNonOperating',
            new_name='CommercialPaper',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='InterestIncome',
            new_name='CommonStock',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='InterestIncomeNonOperating',
            new_name='CommonStockEquity',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncome',
            new_name='CurrentAssets',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncomeCommonStockholders',
            new_name='CurrentCapitalLeaseObligation',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncomeContinuousOperations',
            new_name='CurrentDebt',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncomeFromContinuingAndDiscontinuedOperation',
            new_name='CurrentDebtAndCapitalLeaseObligation',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncomeFromContinuingOperationNetMinorityInterest',
            new_name='CurrentDeferredLiabilities',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetIncomeIncludingNoncontrollingInterests',
            new_name='CurrentDeferredRevenue',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetInterestIncome',
            new_name='CurrentLiabilities',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NetNonOperatingInterestIncomeExpense',
            new_name='FinishedGoods',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NormalizedEBITDA',
            new_name='GainsLossesNotAffectingRetainedEarnings',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='NormalizedIncome',
            new_name='GrossPPE',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='OperatingExpense',
            new_name='IncomeTaxPayable',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='OperatingIncome',
            new_name='Inventory',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='OperatingRevenue',
            new_name='InvestedCapital',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='OtherIncomeExpense',
            new_name='InvestmentinFinancialAssets',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='OtherNonOperatingIncomeExpenses',
            new_name='InvestmentsAndAdvances',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='PretaxIncome',
            new_name='LandAndImprovements',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='ReconciledCostOfRevenue',
            new_name='Leases',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='ReconciledDepreciation',
            new_name='LongTermCapitalLeaseObligation',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='ResearchAndDevelopment',
            new_name='LongTermDebt',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='SellingGeneralAndAdministration',
            new_name='LongTermDebtAndCapitalLeaseObligation',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TaxEffectOfUnusualItems',
            new_name='MachineryFurnitureEquipment',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TaxProvision',
            new_name='NetDebt',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TaxRateForCalcs',
            new_name='NetPPE',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TotalExpenses',
            new_name='NetTangibleAssets',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TotalOperatingIncomeAsReported',
            new_name='NonCurrentDeferredAssets',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='TotalRevenue',
            new_name='NonCurrentDeferredTaxesAssets',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OrdinarySharesNumber',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherCurrentAssets',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherCurrentBorrowings',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherCurrentLiabilities',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherEquityAdjustments',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherInvestments',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherNonCurrentAssets',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherNonCurrentLiabilities',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherProperties',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherReceivables',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='OtherShortTermInvestments',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Payables',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='PayablesAndAccruedExpenses',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Properties',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='RawMaterials',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='Receivables',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='RetainedEarnings',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='ShareIssued',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='StockholdersEquity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TangibleBookValue',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalAssets',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalCapitalization',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalDebt',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalEquityGrossMinorityInterest',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalLiabilitiesNetMinorityInterest',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalNonCurrentAssets',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalNonCurrentLiabilitiesNetMinorityInterest',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TotalTaxPayable',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TradeandOtherPayablesNonCurrent',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='TreasurySharesNumber',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='WorkingCapital',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financedata',
            name='dataFrequency',
            field=models.CharField(choices=[('Q_1', 'Q_1'), ('Q_2', 'Q_2'), ('Q_3', 'Q_3'), ('Q_4', 'Q_4'), ('A', 'Annual')], max_length=6),
        ),
        migrations.AlterField(
            model_name='financedata',
            name='datePub',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='financedata',
            unique_together={('dataType', 'dataStatus', 'symbol', 'dataFrequency', 'dataYear')},
        ),
    ]
