# Generated by Django 4.2 on 2024-08-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_rename_basicaverageshares_balancesheet_accountspayable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financedata',
            unique_together=set(),
        ),
    ]
