# Generated by Django 4.2 on 2024-09-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_financedata_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratio',
            old_name='GrossMargin',
            new_name='Cashratio',
        ),
        migrations.RenameField(
            model_name='ratio',
            old_name='ProfitMargin',
            new_name='Currentratio',
        ),
        migrations.AddField(
            model_name='ratio',
            name='GrossProfitMargin',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ratio',
            name='NetProfitMargin',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ratio',
            name='Quickratio',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ratio',
            name='TDTAratio',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
