# Generated by Django 4.2 on 2024-09-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_overallanalysis_metricdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallanalysis',
            name='metric',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('REVENUE_GROWTH', 'Revenue_GROWTH'), ('REVENUE_VS_COR', 'Revenue_VS_COR'), ('GROSSPROFITMARGIN', 'GrossProfitMargin'), ('DERATIO', 'DERatio')], max_length=40),
        ),
    ]
