# Generated by Django 4.2 on 2024-09-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_alter_balancesheet_financeinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financedata',
            name='symbol',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.symbol'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.symbol'),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.symbol'),
        ),
        migrations.AddField(
            model_name='ratio',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financials.symbol'),
        ),
        migrations.AlterField(
            model_name='dividendcompanies',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dc_symbol', to='financials.symbol'),
        ),
        migrations.AlterField(
            model_name='growthcompanies',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gc_symbol', to='financials.symbol'),
        ),
        migrations.AlterField(
            model_name='overallanalysis',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols_all_overall', to='financials.symbol'),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='financeInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.financedata'),
        ),
        migrations.AlterField(
            model_name='symbolanalysis',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols_all', to='financials.symbol'),
        ),
        migrations.AlterField(
            model_name='valuecompanies',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc_symbol', to='financials.symbol'),
        ),
    ]
