# Generated by Django 4.2 on 2024-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_alter_overallanalysis_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallanalysis',
            name='metric',
            field=models.CharField(choices=[('Cashratio', 'Cashratio'), ('Quickratio', 'Quickratio'), ('Currentratio', 'Currentratio'), ('TDTAratio', 'TDTAratio'), ('DEratio', 'DEratio'), ('NetProfitMargin', 'NetProfitMargin'), ('GrossProfitMargin', 'GrossProfitMargin'), ('RevenueGrowthConsecutive', 'RevenueGrowthConsecutive'), ('RevenueVsCoR', 'RevenueVsCoR'), ('Revenue', 'Revenue')], max_length=40),
        ),
    ]
