# Generated by Django 4.2 on 2024-10-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamtasks', '0002_contribution_rating_contribution_rating_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
