from django.urls import path, include
from .views import JobsListView, UnassignedSymbolListView
from rest_framework.routers import DefaultRouter

from .views import (
    TeamViewSet, RegisteredInstitutionViewSet,ProjectViewSet,StaffApplicationViewSet, UserDetailsViewSet,
    TaskViewSet, TaskCommentViewSet, TaskListViewSet, ContributionViewSet,TaskCompleteViewSet,TaskOwnershipHistoryViewSet
)

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'staff-applications', StaffApplicationViewSet, basename='staff-application')
router.register(r'user-details', UserDetailsViewSet, basename='user-detail')
router.register(r'tasks', TaskViewSet, basename='task')
router.register(r'task-comments', TaskCommentViewSet, basename='task-comment')
router.register(r'task-lists', TaskListViewSet, basename='task-list')  # TaskList viewset
router.register(r'contributions', ContributionViewSet, basename='contribution')  # Contribution viewset
router.register(r'projects',ProjectViewSet, basename='project')
router.register(r'teams', TeamViewSet, basename='team')
router.register(r'institutions', RegisteredInstitutionViewSet, basename='institution')
router.register(r'task-complete', TaskCompleteViewSet, basename='task-complete')
router.register(r'task-ownership-history', TaskOwnershipHistoryViewSet, basename='task-ownership-history')

#Example URLs Generated:
#StaffApplication URLs:#
#
#GET /staff-applications/: List all staff applications or create a new one.
#POST /staff-applications/{id}/approve/: Approve a specific staff application.
#POST /staff-applications/{id}/disapprove/: Disapprove a specific staff application.
#UserDetails URLs:
#
#GET /user-details/: List user details or create new user details.
#GET /user-details/{id}/: Retrieve, update, or delete a specific user's details.
#Task URLs:
#
#GET /tasks/: List all tasks or create a new task.
#POST /tasks/{id}/complete/: Mark a task as completed.
#POST /tasks/{id}/reopen/: Reopen a previously completed task.
#TaskComment URLs:
#
#GET /task-comments/: List all comments or create a new comment for a task.
# URL patterns
urlpatterns = [
    path('jobs/', JobsListView.as_view(), name='jobs-list'),
    path('unassigned-symbols/', UnassignedSymbolListView.as_view(), name='unassigned-symbols'),
    path('', include(router.urls)),  # Include all the viewset URLs generated by the router

]


